### ISSUE TITLE
Process name is python3, should be lollypop

### ISSUE THREAD

**Issue by dotreloaded** [gnumdk/lollypop#1006]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.9
• Linux distribution: Arch Linux

Process name is python3, should ideally be lollypop. For example, right now doing something like `pgrep lollypop` won't return anything.

**Comment by gnumdk** [comment]
Is that possible? Are you sure? Any example?

Will close otherwise.

**Comment by dotreloaded** [comment]
I've realized that the shebang in `lollypop.in` causes this.

If `#!/usr/bin/env python3` is changed to `#!/usr/bin/python3` process name will be set to lollypop.

**Comment by julianrichen** [comment]
Both `gnome-music` and `pitivi`, which are python3 programs using `!/usr/bin/env python3`, show the process name instead of python3. What are they doing different?

https://github.com/GNOME/gnome-music/blob/master/gnome-music.in
https://github.com/pitivi/pitivi/blob/master/bin/pitivi.in

I would have assumed it was `Glib.set_prgname ()` but pitivi doesn't set that and it works.

**Comment by julianrichen** [comment]
I've looked into this further and it doesn't seem to be code in Python, or setting some function. I tried a number of configurations including when the `GLib.set_prgname ()` method is called and it seems to do nothing.

My guess it would be related to some data installed, like the .desktop file. But I played with it for a while and nothing. Very strange :(

**Comment by gnumdk** [comment]
Will give a look asap

**Comment by gnumdk** [comment]
Here gnome music and pitivi show python3 in system-monitor...
