### ISSUE TITLE
Question - Can Lollypop play module and MIDI files?

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#109]
Hello

I see that Gstreamer 1.0 is supposed to support module files through libmodplug and MIDI files through wildmidi. When attempting to play them with the snappy video player (which also uses Gstreamer 1.0), this works correctly. I think it doesn't work in Lollypop because it is blocking them out based on the mimetype.

I've been taking a look at Snappy's source and it seems to just assume it can play anything, complaining about a codec being missing whenever Gstreamer eventually fails to actually play it, for example: https://git.gnome.org/browse/snappy/tree/src/gst_engine.c#n662 I'm not entirely sure if this suits your needs for an implementation in Lollypop, however.

Kind regards

**Comment by gnumdk** [comment]
Give me the mime type to add.
Regards,
Cédric
Le 13 mai 2015 21:33, MineyMe <notifications@github.com> a écrit :Hello

I see that Gstreamer 1.0 is supposed to support module files through libmodplug and MIDI files through wildmidi. When attempting to play them with the snappy video player (which also uses Gstreamer 1.0), this works correctly. I think it doesn't work in Lollypop because it is blocking them out based on the mimetype.

I've been taking a look at Snappy's source and it seems to just assume it can play anything, complaining about a codec being missing whenever Gstreamer eventually fails to actually play it, for example: https://git.gnome.org/browse/snappy/tree/src/gst_engine.c#n662 I'm not entirely sure if this suits your needs for an implementation in Lollypop, however.

Kind regards

**Comment by MineyMe** [comment]
I get the following mimetypes:

  * .it files: **audio/x-mod; charset=binary**
  * .mid files: **audio/midi; charset=binary**
  * .s3m files: **application/octet-stream; charset=binary**

However, as you can see here [1], there are plently more formats that may have different mimetypes and other gstreamer plugins not mentioned here may support even more mimetypes. I understand it is cumbersome for you to maintain this list manually, is there no other way to block out unplaylable files (e.g. by letting gstreamer somehow detect or fail on them)?

[1] https://github.com/Konstanty/libmodplug

**Comment by gnumdk** [comment]
Fixed in git...
For s3m, your distribution is broken, mime should be: audio/s3m

**Comment by gnumdk** [comment]
http://www.sitepoint.com/web-foundations/mime-types-complete-list/
