### ISSUE TITLE
Albums with the same name by different artists get combined

### ISSUE THREAD

**Issue by steve80289** [gnumdk/lollypop#1119]
### Environment
- Lollypop version: 0.9.240-1.fc26
- GNOME/GTK+ versions: gnome-shell 3.24.2-1.fc26 and gtk3 3.22.15-2.fc26
- GNU/Linux distribution: Fedora 26 (Beta)

### Bug/Feature
I have albums from Sublime and Fall Out Boy, which are both named "Icon". They have been combined and look likes they are considered the same album.

**Comment by gnumdk** [comment]
You are missing an "album artist" tag.

**Comment by steve80289** [comment]
Can you please elaborate?

**Comment by codykru** [comment]
use a program like Kid3 to edit your 'album artist' tag. 

Imagine a compilation with many artists, or even just a single song by an artist other than the creator of the album, it wouldn't make sense to list this as a completely separate album, just because the song has a different artist, here's an example:
![screenshot from 2017-06-20 00-04-48](https://user-images.githubusercontent.com/9169186/27316214-3587b706-554c-11e7-9477-c827d6938707.png)

If it doesn't have an album artist tag, you can add it by clicking 'Add' on the right side and selecting album artist (be sure to select the entire album/all of the tracks when you do this)

**Comment by gnumdk** [comment]
Thanks codykru
