### ISSUE TITLE
Identify Hi-Res albums

### ISSUE THREAD

**Issue by lgeneix** [gnumdk/lollypop#1156]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Manjaro

### Feature
I've all my music library in flac and Lollypop work well, thanks for that :) ! 
But it would be handy to identify albums that are in Hi-Res (24 bits file or more than 44.1 kHz sampling frequency).

Here is an example :
![lollypop_hires](https://user-images.githubusercontent.com/7721214/27996564-184100b4-64e5-11e7-98cf-2a50ff1ac58d.png)

**Comment by d9h02f** [comment]
Why? You can't hear the difference anyway.

**Comment by lgeneix** [comment]
The high resolution allow to keep more information than a cd, so it's more interessant to work with this format.
Then, with a correct set up we can hear a difference but it's true that currently the devices aren't still totally adapted.
This little feature will allow to see which albums are in this resolution (Vinyl rip, studio album ...).
But i know this is specific and maybe not in the project's mind.

**Comment by mray** [comment]
Upon creating a new issue there may be a relevant hint:
> WONTFIX:
> - Showing bitrate

So don't hang your hope to this feature being included too high I guess.

**Comment by lgeneix** [comment]
Yes i've seen this hint before post but here it is not a matter of bitrate. I don't ask to show it.

**Comment by JasonLG1979** [comment]
Bitrate and bit depth are not the same thing.  mp3's have no real constant bit depth like PCM/WAV so any static bit depth number is meaningless. The bitrate of a flac file would depend on it's compression level and since flac is lossless would be no indication of it's sound quality. so bitrate for flac is meaningless other than to show how much space you saved by compressing it.

So in short: 
bit depth = meaningless for lossy compression.
bitrate = meaningless for lossless compression.

That only leaves sampling rate. Sampling rate is one of those things where people assume that it actually makes a difference. A thousand ABX tests with crazy high dollar gear says that no human in the history of digital audio can hear the difference between 44.1 and above sampling rates. Unless your hearing extends beyond 22kHz(it doesn't, the average adult male can't hear much above 14kHz) and you're listening to hummingbird wings there is no audible difference. Because 1. You can't hear those frequencies and 2. Even if you could there's nothing up there in music to hear.

The idea of digital audio as a jagged stair step is a myth. If you think that you should read about the Nyquist–Shannon sampling theorem (https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem) the basis for digital audio.

In any case @gnumdk regards such things as stats for nerds and I wouldn't hold your breath...

**Comment by d9h20f** [comment]
Another interesting read on the topic: https://xiph.org/~xiphmont/demo/neil-young.html

Also, if you need a 'hi-res' indication to know you are listening to a 'hi-res' album...

**Comment by gnumdk** [comment]
Closing this one as wontfix.
