### ISSUE TITLE
differentiate between singles, cd, ep and so on...

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1158]
as the title said it would be nice if lollypop could differentiate records with tags like album, ep, singles and so on...maybe this could be written near the album title or in the cover art and information could be stored in the comment tag section...

**Comment by palob** [comment]
How to do that? Afaik there is no metadata tag for this?

**Comment by legacychimera247** [comment]
the difference is the fact i can perfectly rearrange my music as i have in my original records collection...

**Comment by d9h02f** [comment]
It's possible if you differentiate by using the tag 'labelid' (to be clear, Lollypop doesn't read this tag, but maybe it could). Of course you'll run into problems for anything not on a label or with an unknown catalogue number. You could enter a bogus string instead for any non-existing or unknown catalogue numbers to work around that issue.

@gnumdk, maybe Lollypop could split albums based on labelid (instead of albumartist/...)?

**Comment by gnumdk** [comment]
No, will not support such feature.
