### ISSUE TITLE
Down samples high-res files

### ISSUE THREAD

**Issue by benjamindaines** [gnumdk/lollypop#1182]
if you play a high-res music file with lollypop (24/96 FLAC) and you check what's actually going to your sound card, you will see that it has been down sampled to 16 bits.

$ cat /proc/asound/PCH/pcm0p/sub0/hw_params   

That's a deal breaker for me.

**Comment by gnumdk** [comment]
Pulseaudio configuration...

**Comment by benjamindaines** [comment]
# pacman -Rs lollypop

**Comment by gnumdk** [comment]
Cool :tada:

**Comment by gnumdk** [comment]
Sound defaults are 44Khz/16bit because that’s what the Audio CD standard is
Human hearing range is 20Hz to 20Khz (give or take) and higher frequencies degrade with age, by 40 you’re lucky to hear the full spectrum up to 17Khz

So theoretically CD quality is all we’ll ever need, however vynil records are deemed more warm for the subsonic frequencies we feel rather than hear so extending the range is not necessarily a bad thing.

And if you can't configure pulseaudio, that's not my problem!
