### ISSUE TITLE
Prevent suspend while playing music.

### ISSUE THREAD

**Issue by enaut** [gnumdk/lollypop#1188]
### Environment
- Lollypop version: 0.9.243
- GNOME/GTK+ versions: 
- GNU/Linux distribution: Fedora 26

### Feature
While playing music my computer frequently goes to standby. It would be nice to have some notification to Gnome that now music is playing and therefore standby is prevented.
Note that I don't have anything against the screensaver. Just the standby is annoying.

My current solution is to use the caffeine gnome-shell extension - but it would be nice to have this functionality in Lollypop.

**Comment by JasonLG1979** [comment]
I'll take a look at the caffeine extension and see if I can't add a option in Lollypop to prevent going to sleep/suspend/screensaver.

**Comment by julianrichen** [comment]
I belive the flag you are looking for is `
GTK_APPLICATION_INHIBIT_SUSPEND` or`GTK_APPLICATION_INHIBIT_IDLE`.

Which could be set when music is playing.

https://developer.gnome.org/gtk3/stable/GtkApplication.html#GtkApplicationInhibitFlags

**Comment by gnumdk** [comment]
Was set the past and removed, can't remember why...

**Comment by JasonLG1979** [comment]
My thought is to connect to the playback status. So that it only inhibits when Lollypop is actually playing. That way when Lollypop is stopped or paused everything works as before.

A related feature would be auto pause on sleep/suspend/screensaver. Pithos has a plugin that does that. I can port it over pretty easy.
