### ISSUE TITLE
Lollypop crashing when receiving a notification on Deepin

### ISSUE THREAD

**Issue by theMadBadger022** [gnumdk/lollypop#1203]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions:  DDE 3.1.14 based off Deepin 15.4.1
- GNU/Linux distribution: Manjaro Deepin 17.0.2

For any type of notification, system / application / lollypop, the program always crashes. Updated twice so far and problem still persists:

```
Traceback (most recent call last):
   File "usr/lib/python3.6/site-packages/lollypop/GioNotify.py", line 105, in do_g_signal
      id, signal_value = parameters.unpack()
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Menidon** [comment]
Can confirm, I got the same issue.

**Comment by JasonLG1979** [comment]
Author of GioNotify.py here.

Deepin's notification service does not correctly follow the notification spec (https://developer.gnome.org/notification-spec/) You need to file a bug with them. They need to fix their implementation, it's broken.

The latest git version should workaround the issue by basically disabling all notification in Deepin because they also fail to provide the mandatory GetCapabilities method.

**Comment by JasonLG1979** [comment]
In the above case the signal is suppose to contain an array of parameters containing an id which corresponds to the id of the notification that sent the signal and the signal name. (Valid signal names are "NotificationClosed" and "ActionInvoked") They are missing one of them.

**Comment by gnumdk** [comment]
Is it here? https://github.com/pithos/pithos/blob/master/pithos/plugins/dbus_util/GioNotify.py

**Comment by JasonLG1979** [comment]
Yes. The error is happening in ```do_g_signal``` I can add a try except to catch the error. It would stop the crash but it would make any buttons in the notification non-functional.(if Deepin has buttons in it's notification) Really though it's not our bug. As I said above it caused because of their shit notifications implementation.

**Comment by gnumdk** [comment]
I agree ;)
