### ISSUE TITLE
Import Rhythmbox Database

### ISSUE THREAD

**Issue by archdria** [gnumdk/lollypop#177]
Hi! I would like to use Lollypop, it looks really nice and it has lots of cool features.
However, I've been using Rhythmbox for some years now and I don't want to give up all my statistics (ratings, last played, etc)
Are there any plans to import Rhythmbox database?

Thank you for creating such an amazing music player!

**Comment by gnumdk** [comment]
I will add an external script to do this.

**Comment by archdria** [comment]
Cool, thank you!

**Comment by gnumdk** [comment]
Can your give me details on the "etc" in your stats?

**Comment by gnumdk** [comment]
After looking at Rhythmbox database, seems to be impossible. Two different concepts.

Lollypop use dynamic rating, when you listen to a track:
- Lollypop add +1 to album
- Lollypop add +1 to track

You can influence this rate in interface (only albums for now) but rate can decrease if you stop listening to an album/song.

As rhythmbox only store a rate from 1 to 5, it's impossible to import this in Lollypop.

But, just give a try to lollypop, I implement dynamic rating because I find rating boring. Just listen to your favorite tracks and rating will be done automatically.

regards,

**Comment by archdria** [comment]
Okay, thank you!
I think maybe not the ratings, but could the last played and the playcount be used to pseudo-import the database, maybe using the rating as a multiplier factor to the playcount...
Anyway, here's what Rhythmbox stores for a track:
```xml
 <entry type="song">
    <title>Origins</title>
    <genre>indie pop, lo-fi</genre>
    <artist>Tennis</artist>
    <album>Young &amp; Old</album>
    <track-number>2</track-number>
    <duration>208</duration>
    <file-size>4941423</file-size>
    <location>file:///home/adria/Music/Tennis/2012%20-%20Young%20And%20Old/02%20-%20Origins.ogg</location>
    <mtime>1390743424</mtime>
    <first-seen>1358982447</first-seen>
    <last-seen>1435217938</last-seen>
    <rating>5</rating>
    <play-count>17</play-count>
    <last-played>1434049411</last-played>
    <bitrate>192</bitrate>
    <date>734503</date>
    <media-type>audio/x-vorbis</media-type>
    <album-artist>Tennis</album-artist>
    <composer>Unknown</composer>
  </entry>
```

**Comment by gnumdk** [comment]
Done
rhymthmbox2lollypop

**Comment by archdria** [comment]
Wow, that was quick!
I'll try that later at home.
Merci beaucoup !

**Comment by archdria** [comment]
Works great, thank you very much! You've just got another user :D

**Comment by arrufat** [comment]
Hello again! Is it just me, or the rhythmbox2lollypop script just disappeared?
I tried to use the old version, but it complains about the 'filepath' column not existing... I would understand if you won't support this feature any more...

Thanks in advance.
