### ISSUE TITLE
Weird sort artist

### ISSUE THREAD

**Issue by andresanemic** [gnumdk/lollypop#456]
Hi, I'm using Arch Linux and I have the 0.9.83 version of Lollypop, but since a week or two, the artists are sorted in a strange way. For example, John Lennon appears in the letter L, Alanis Morissette appears on the letter M, and so on. Let me show it the problem:

http://imgur.com/a/S7dRj

I believe that only the artists like The Beatles o The White Stripes should ignore the word "The", but in this case the app ignores the name and consider the last name.

(Sorry for my english)

**Comment by alexskc** [comment]
It's not the app is ignoring the first name. This is intended behaviour. When sorting names, you generally look up "Lastname, Firstname." So, for example, "Pratchett, Rhianna" would be before "Pratchett, Terry" if you're looking for them on a bookshelf.

You'll notice band names that are two or three words don't get ignored like this. "Built to Spill" still shows up under B.

How Lollypop figures out how to do this is with Musicbrainz "sort artist" tag. This also means that artists that use foreign characters in the name also get sorted alphabetically. For example "久石譲" shows up under H for me because it's pronounced "Hisashi Jou"

I dunno if there's anything you can do if this really does bother you. I prefer having "Beatles, The" just before "Bowie, David" but I can understand why it'd bother some people. You could remove the tag from all your music, but that could be a lot of work. And I don't know if having it as a setting is possible if it's written in the database.

**Comment by andresanemic** [comment]
Yeah, I prefer "Beatles, The" too, but only in that case. But if you say that is difficult to create a option to chose in the settings of the player, I'll try to change the tag of my music or search another player. 

A very sad thing, because I really love Lollypop.
Thanks.

**Comment by gnumdk** [comment]
Your files contains an "artist sort" tag. Not lollypop.
Lollypop only handle "The" by default and you can use the "artist sort" tag to disable this:
https://github.com/gnumdk/lollypop/issues/441

**Comment by iborg10103** [comment]
I'm using Lollypop 0.9.104 under Ubuntu 16.04 with Spanish locales (LANG=es_ES.UTF-8)

Lollypop artists sidelist shows mp3 files tagged with artist="El Antiguo" and performersortorder="Antiguo, El" (see attached puddletag image) under "E" and not under "A". 
Files tagged with artist="La Banda" and  performersortorder="Banda, La" are sorted correctelly under "B" and not "L" so I think lollypop sorts ignore tags in files and use only this rules in po/es.po

#: ../src/utils.py:111
msgid "The the"
msgstr "The the Les les La Le la le los el"

![tags](https://cloud.githubusercontent.com/assets/19275081/15161045/e55e882e-16fc-11e6-966f-5b5034fd470d.jpg)

**Comment by gnumdk** [comment]
What is your tagging software?

**Comment by gnumdk** [comment]
Gstreamer only support:
- artist-sortname
- album-artist-sortname

**Comment by gnumdk** [comment]
You will need to reset your database in lollypop about dialog...

**Comment by MichaelTiebesl** [comment]
But it is strange to me that I who don't use sortname tag have to use it. I like to have The Beatles on the T for example. So for that, i have to use sortname tags what I don't want and other people who want to use sortname tags don't have to do that because The Beatles is by default already Beatles The. It is more logical for me when there was by default The Beatles. When somebody wants that as Beatles The, then he or she can use the tag sortname. :)

**Comment by iborg10103** [comment]
Just to confirm Fix #456 solves the problem. Now Llollypop sorts artist using mp3 tags in files. Thanks!!!
