### ISSUE TITLE
Albums with multiple artists should be displayed under each artist

### ISSUE THREAD

**Issue by bretter** [gnumdk/lollypop#507]
Problem:
Currently, albums with multiple album artists, separated by a semicolon are categorized by neither artist but instead are categorized by the combination of both artists.

Current behavior:
Consider an album with `album artist` populated with: `artist1; artist2`
On the artist navigation pane on the left, neither artist1 nor artist2 appears.
Instead there is an entry for "artist1, artist2".

Expected behavior:
Instead of an entry for "artist1, artist2", the album should appear when filtering by "artist1" and again when filtering by "artist2".
No entry for "artist1, artist2" should appear in the artist navigation pane.

**Comment by gnumdk** [comment]
Do you really have an example?

For me, only artist tag should be used for this.

**Comment by d9h02f** [comment]
An album with two or more artist tags, such as
artist - Dirty Three
artist - Low
will show up in the listing as an album by "Dirty Three, Low", but it won't show up under "Dirty Three" or "Low".

**Comment by bretter** [comment]
If an album has `artist` populated with multiple artists, separated by a ';', it appears only under compilations and not under either artist.

**Comment by bretter** [comment]
An example might be something like Sour Soul, an album where BADBADNOTGOOD performs the music and Ghostface Killah raps. I would like to be able to find this album when looking at music by either artist.

MF Doom similarly collaborates with popular producers such as Madlib and Danger Mouse. I would also expect these albums to appear under both MF Doom and the producer.

**Comment by gnumdk** [comment]
Do not use this branch, broken code ;)

**Comment by gnumdk** [comment]
Good news, it works (but lollypop is strill broken as I need to re-test all)

**Comment by gnumdk** [comment]
0.9.90 is now stable branch.
"multiple album artists" is now master and please help me fix all regression. If you don't know how to install from git, tell me.

**Comment by bretter** [comment]
Thought I could just install lollypop-git from aur but that seems to have pulled 0.9.91.

What's the best way to go about installing 0.9.90 on arch?

**Comment by gnumdk** [comment]
0.9.91 is the version you are looking for

**Comment by bretter** [comment]
Ah, okay then!

I am currently seeing only the structure of the app (left navigation pane, and album art area) but completely empty.

![image](https://cloud.githubusercontent.com/assets/5185415/13902051/1538e2cc-ee0f-11e5-9939-23aecd420166.png)


CLI output:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/lollypop/loader.py", line 49, in run
    result = self._target()
  File "/usr/lib/python3.5/site-packages/lollypop/container.py", line 456, in load
    artists = Lp().artists.get(genre_ids)
  File "/usr/lib/python3.5/site-packages/lollypop/database_artists.py", line 156, in get
    ORDER BY artists.sortname COLLATE NOCASE")
sqlite3.OperationalError: no such table: album_artists
```

**Comment by gnumdk** [comment]
My bad, I reset master as my code miss db upgrade :)
Going to sleep, tomorrow...

**Comment by gnumdk** [comment]
You can install lollypop-git again to test this feature. Report bugs in this bug report.

**Comment by bretter** [comment]
Alright! Very close...
This is what I am observing:

**Case 1**
artist = ""
albumartist = "artist1, artist2"
Albums appear under each artist.
This is expected/preferred behavior!

**Case 2**
artist = "artist1, artist2"
albumartist = ""
Albums appear under compilations.
I would expect this to behave as above and only albums with individual tracks by varying artist to appear under compilations.

**Case 3**
artist = "artist1, artist2"
albumartist = "artist1, artist2"
Albums appear under "artist1, artist2" (no change in behavior compared to 0.9.90).
I would expect albumartist to take precedence and behave as case 1.

I don't know if there is an official guide for how artist and albumartist should be treated but I have always viewed them as being more or less redundant and would expect each of these three cases to behave identically. If nothing else, I always expect albumartist to take precedence over artist and would therefore expect Case 3 to behave like case 1.

That said, if there is a justified reason to define separate behavior for each case, adjustments to one's library can be made to achieve the desired effect.

**Comment by gnumdk** [comment]
Case2 needs to be fixed.
Here case3 works but separator is ; not ,

**Comment by bretter** [comment]
Ah, yes! You are correct. Got mixed up between what was displayed and what needed to be put into the field.

**Comment by d9h02f** [comment]
Now, when an album has two or more _separate_ artist tags, such as the example before of
artist - Dirty Three
artist - Low
it will show up as an album by "Dirty Three", but it won't show up under "Low", so I assume there is currently only a check for the first artist tag that is found.

**Comment by bretter** [comment]
Yes, it appears that I was not very thorough in my initial test.

I am indeed not seeing the second artist for cases 1 and 3.

Further, I am seeing different behavior for mp3 and flac files.

Flac files appear under only the first artist while mp3 files appear under "Artist 1 / Artist 2"

**Comment by gnumdk** [comment]
Send me exemple files by email

**Comment by gnumdk** [comment]
Please test again, I just fixed an horrible bug while working on #515

**Comment by gnumdk** [comment]
Your flac files should have a / separator, no?

**Comment by bretter** [comment]
No. Flac files are appearing only under the first artist.

Tried to send an email with test files but got "no such email address".

Try these out:
https://www.dropbox.com/s/qg1b3akhj4gpl9l/10.%20Nuggets%20of%20Wisdom.flac
https://www.dropbox.com/s/dbqe77z3u0uk6vt/05.%20Boulder%20Holder.mp3?dl=0

Will delete links after a few minutes.

**Comment by gnumdk** [comment]
cedric.bellegarde@adishatz.org

**Comment by gnumdk** [comment]
@d9h02f Send me your file about :+1: 
artist - Dirty Three
artist - Low

**Comment by d9h02f** [comment]
Done.

**Comment by gnumdk** [comment]
@d9h02f I will revert back change about #505 as APE tags really handling multi artists (as an array and not as arist1;artist2) and some software tag theme using.

@bretter files are a flac file and a mp3 file with APE tags and mutliartists in array.

**Comment by gnumdk** [comment]
@d9h02f There is not bug:
Album artist: Dirty Three, Low
Artist: Dirty Three

So we have a split album with one track... Add Low to Artist list, it is missing a track.

**Comment by gnumdk** [comment]
BTW #505 isn't a problem as easytag now (recent archlinux update) delete APE tag from files when not needed.

**Comment by d9h02f** [comment]
@gnumdk Maybe I should have sent the other track as well to make it clear. That one has albumartist Dirty Three, Low and artist Low. Both tracks only show up under Dirty Three, which is the first in the list of albumartists. If you put Low first in the list of albumartists, both tracks will only show up under Low.

**Comment by gnumdk** [comment]
@d9h02f Was due to #505 fix, retest

**Comment by bretter** [comment]
So I have cleaned up my tags and it looks like albums are appearing under artist1 but not under artist2.

Email with example file sent.

**Comment by Lexolas** [comment]
Hey guys! When there is an album that has multiple album artists different from the normal "artist" tags, tracks don't show up in the library neither under "artist1" nor "artist2" or any other location!!! But everything seems to be fine and working properly when there is just one "album artist".


**FOR EXAMPLE**

"FabricLive.37 mixed by Caspa & Rusko" is an electronic album on which "Caspa" and "Rusko" would be separate album artists. Many tracks of this album also have different artists cause some of the tracks are just selected/remixed by Caspa and Rusko. So actually it's a Compilation with two album artists. Tracks that have neither Caspa or Rusko in the normal "artist" tag never show up in the library or disappear completely!! So two third of all the Albumtracks are missing in my library.

** 1)** Track shows up under "Caspa":
album = "FabricLive.38"
title = "Girl from Codeine City"
artist = "L-Wiz"
album artist = "Caspa"

** 2)** Track shows up under "Caspa" and also "Rusko":
album = "FabricLive.38"
title = "Girl from Codeine City"
artist = "L-Wiz"
album artist = "Caspa; Rusko"

** 3) [FALSE!]** Track "Girl from Codeine City" is gone and just "Cockney Violin" is displayed under "Caspa"; under "Rusko" i can find both tracks:
album = "FabricLive.38"
title = "Girl from Codeine City"
artist = "L-Wiz"
album artist = "Caspa; Rusko"

album = "FabricLive.38"
title = "Cockney Violin"
artist = "Caspa"
album artist = "Caspa; Rusko"

** 4) [FALSE!]** Track "Girl from Codeine City" is now also gone under "Rusko":
album = "FabricLive.38"
title = "Girl from Codeine City"
artist = "L-Wiz"
album artist = "Caspa; Rusko"

album = "FabricLive.38"
title = "Cockney Violin"
artist = "Caspa"
album artist = "Caspa; Rusko"

album = "FabricLive.38"
title = "Jahova"
artist = "Rusko"
album artist = "Caspa; Rusko"


Albums that have multiple album artists are often Classical, Electronic or Hip-Hop albums.
"Foobar" and "Quod Libet" have solved this issue and i would love to see this Bug fixed in Lollypop too, because apart from that problem it's a great Player :) But this doesn't make absolutely any sense to me.

**Comment by gnumdk** [comment]
Please send me album by email via Gdrive/dropbox/wetransfer/ ... ;)

Should be easier for me.

**Comment by Lexolas** [comment]
Understand this point.
But I don't think that my tags are broken. These electronic producers make gapless albums where they mix up their own tracks with these of other artists. So it is important that all these tracks stay together as a whole album and nevertheless have different artists. I always thought this is the "album artist" tag for.

Actually what you are doing in your example is splitting them up by the "artist" tag... you just need the "album artist" so that Lollypop does not make a compilation out of it ;)
But the "physical" CD/EP is still one disk! And therefore sorted by "album artist" File1 and File2 should also be displayed at God Squad. At the moment strictly speaking even the automatic track number in Lollypop is false. Cause File 3 isn't Track 1 on "Split", but is displayed as such under God Squad.
 
Isn't there a way to make this behaviour in the menus turn on or off? So that we can really sort by "album artist" without those mechanisms? And so every track of an album is also displayed by every "album artist" and albumtracks stay together?
How can you hear such albums as a whole - do you always create new playlists?

**Comment by gnumdk** [comment]
You are wrong because I also want to get the Album with all the tracks in the album view. With your solution, I will have two albums ;)

**Comment by gnumdk** [comment]
For track numbering, there is an option in dconf to use value from tags.

**Comment by Lexolas** [comment]
I don't get it. Can you send me your tracks, so i can see by myself how you do it?

**Comment by gnumdk** [comment]
But, your issue is fixed, if it's not clear ;)

**Comment by Lexolas** [comment]
I have tried every possible way of tagging. And the only way to get all the tracks of Split displayed in Anti-Flag and God Squad too, is to put both artists into the tags of every file:
title "Want anarchy"
album "Split 1996"
artist "Anti-Flag"
artist "God Squad"
album artist "Anti-Flag; God Squad"

This is no solution for me. I think i give up ;)
Thanks for your patience.

**Comment by gnumdk** [comment]
Why are you talking about? It's my albums!
You albums works with lollypop code from master!

**Comment by gnumdk** [comment]
![all](https://user-images.githubusercontent.com/3918824/32668774-d2450004-c63e-11e7-8c3b-2f6cadb5b841.png)
![capture du 2017-11-10 17-44-13](https://user-images.githubusercontent.com/3918824/32668775-d312cc50-c63e-11e7-988f-01c9be77073e.png)
![capture du 2017-11-10 17-44-25](https://user-images.githubusercontent.com/3918824/32668776-d353abf8-c63e-11e7-9ebd-49e629bbda15.png)

**Comment by Lexolas** [comment]
Great collection ;)

I actually have no further idea how to explain that to you.
It's a Mixtape. Some tracks of the CD are performed by one of the album artists, some by the other album artist, some even by both album artists and the rest by completely different artists. But it's gapless and all tracks belong together. In electronic music that's not unusual.
I do exactly the same tagging as you - my tags are not broken!

But my album looks like this:
![screenshot1](https://user-images.githubusercontent.com/12045801/32670880-7d24af78-c645-11e7-9656-d987bd91455f.png)
![screenshot2](https://user-images.githubusercontent.com/12045801/32670890-84b10610-c645-11e7-820b-5ce1aaab28ff.png)
![screenshot3](https://user-images.githubusercontent.com/12045801/32670895-87c530ec-c645-11e7-93ab-b782e0a763c6.png)

I know that there are only a few players that can handle such albums in a good way. But it's simply a little bit inconsistent in Lollypop. I have to add both album artists as "artist" tags for all tracks of the album. But that isn't correct and would be like adding "God Squad" as artist to "Want an Anarchy".

I think i will turn back to another player, although i love the appearance of Lollypop :)
Thanks for your time and patience and keep up your good work.

**Comment by gnumdk** [comment]
And so where the issue, in the album view (not the artist one), the album is complete, no?

**Comment by gnumdk** [comment]
And for information, you can select both artist with Ctrl + click ;)

**Comment by Lexolas** [comment]
I changed the album artist to "Caspa & Rusko". That is not a perfect solution, but at least with a single "album artist" the album remains complete - also in the artist view. Nevertheless i'm still hoping that sometime in the future Lollypop will get an option to turn that splitting on and of or support a special tag which makes this possible ;)
Thanks for all and best regards :)

**Comment by gnumdk** [comment]
Is there something you don't understand with: "The isssue is fixed" ?
I have your album in my collection and all tracks show up!

**Comment by gnumdk** [comment]
Have you tried to build from master?

Look here:
Album view:
![caspa rusko1](https://user-images.githubusercontent.com/3918824/32690112-0523ba3a-c6f1-11e7-9dad-7a0cbb4fad09.png)
Caspa view:
![caspa rusko2](https://user-images.githubusercontent.com/3918824/32690113-05756894-c6f1-11e7-9260-5cd0313dc6d3.png)
Rusko view:
![caspa rusko3](https://user-images.githubusercontent.com/3918824/32690114-05ccdda4-c6f1-11e7-9aad-61043cccc78c.png)

**Comment by gnumdk** [comment]
And the last one with multiple selection:
![caspa rusko4](https://user-images.githubusercontent.com/3918824/32690140-b3c63cc0-c6f1-11e7-8d9c-4ad93dfc99d4.png)
