### ISSUE TITLE
Library update halts playback

### ISSUE THREAD

**Issue by bretter** [gnumdk/lollypop#511]
Problem:
If music is added to/deleted from the library or any album tags are changed while music is playing, the music is stopped.

Expected behavior:
If a song is playing and changes are made to the library that do not affect the currently playing track the track should continue to play.

**Comment by gnumdk** [comment]
Not happening here

**Comment by alan12345678** [comment]
Not quite halting playback, but I do seem to have an issue currently where the library constantly updates every time I launch the player. I should explain that, partly for reasons of learning and partly because I've not yet the hardware to host my library locally, I'm accessing a WLAN mounted music library being served on a Windows machine, mounted on my Linux box.

If I launch the player and quickly select something from a left hand artist, and the main panel switches to those album view, the player works fine. But if I simply leave it open at "all albums", I get a notification message that library is updating, but the player window etc. becomes completely unresponsive. I end up with a gnome panel asking me if I'd like to wait or force kill.

Is there a memory limit on the library? Do I need to run more local swap space? Is it reasonable to expect the player to manage 35,000 tracks?

Also - possibly separate issue - what's up with it not displaying album art for WMA files? Is that a gnome plugin or other codec I'm looking for?

Fantastic player though - would love to iron out the odd issues

**Comment by gnumdk** [comment]
> library constantly updates every time I launch the player.
You're mount point returns wrong mtime values I guess...

**Comment by alan12345678** [comment]
ah, interesting. Thanks. So considering the mount is indeed a remote FAT file system (controlled by Windows obviously), what do you suggest the correct value to add "allow_utime=" should be in my fstab?

**Comment by gnumdk** [comment]
No idea ;) Another solution is to disable library update in lollypop settings...

**Comment by alan12345678** [comment]
yes but disabling the update is only useful once the library is fully up to date. If it is simply the case that it takes DAYS to do this over wifi then I can wait. If it ends up being a pain, I'll turn it off. However, the way it displays the artist names etc. is forcing me to amend my tagging - again! :0)

**Comment by bretter** [comment]
I entered debugging and updated my library while playing music mode and I am seeing some output that may be related to this issue.
```
Error scanning: /home/brettski/Music/Tahsa Mix/FALL BE KIND/05 I Think I Can.m4a, gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
Error playing: file:///home/brettski/Music/Tahsa%20Mix/FALL%20BE%20KIND/05%20I%20Think%20I%20Can.m4a

```
Note that _I Think I Can_ was not the track previously playing.

I deleted that track and updated again. Music still stops and I am seeing this output:

Error playing: file:///home/brettski/Music/Tahsa%20Mix/FALL%20BE%20KIND/05%20I%20Think%20I%20Can.m4a

In the second case, it seems that Lollypop is not detecting that the file is gone. Although I am confused as to why it is trying to 'play' this track in the first place.

**Comment by gnumdk** [comment]
You're gstreamer installation is broken... You are missing m4a codecs...

**Comment by bretter** [comment]
I am on arch linux and have gst-plugins-(good/bad/ugly) installed is there an additional package needed for m4a?

Say there is an issue with my gstreamer inatall, shouldn't deleting the file stop Lollypop from attempting to access it?

**Comment by gnumdk** [comment]
pacman -S gst-libav

**Comment by bretter** [comment]
Yep, that fixed it! Thanks!
