### ISSUE TITLE
Option to see the current bitrate

### ISSUE THREAD

**Issue by Menidon** [gnumdk/lollypop#642]
The only feature missing right now for me is displaying the current bitrate. Would this be possible?

**Comment by gnumdk** [comment]
No, don't want such nerd's feature in Lollypop...

**Comment by Menidon** [comment]
A nerd's feature are you serious... Its just to see the fucking quality of the Music witch is very important to many people. Also i asked to add an option and not make it a default thing.

**Comment by gnumdk** [comment]
>Its just to see the fucking quality of the Music witch is very important to many people

1) People who think music quality is important use FLAC ou high quality MP3 (and so know music quality)
2) Nobody needs to know song bitrate at playback
3) Lollypop users don't want such features (just read all bug reports to convince yourself)
4) Install easytag, album menu -> Modify information

**Comment by Menidon** [comment]
I know that but i have a big music library with many FLAC's and MP3's with different bitrates, And i don't want to start CMUS every time i want to see the quality of the music I'm playing. Also it doesn't hurt Lollypop whatsoever if you add an option to display bitrate, I'm sure many people don't use party mode either...

**Comment by simoniz0r** [comment]
> Lollypop users don't want such features

Lollypop user requests feature, dev tells Lollypop user that Lollypop users don't want that feature.

Something doesn't add up here.

**Comment by bmsimons** [comment]
So here's my honest opinion on this:

You don't simply handle feature requests like this. How do you know that Lollypop's userbase doesn't want this feature to be implemented? Take a look at the dislike ratio of your comments in this feature request as an example. 

> 3) Lollypop users don't want such features (just read all bug reports to convince yourself)

I don't honestly think that this is a good argument because the requested feature is such a small thing which could be programmed & implemented easily. Nobody replied to this request at first and you already closed it, while you left a pretty rude comment as well. Definitely not the spirit of open source, right?

**Comment by d9h02f** [comment]
I can only agree with @gnumdk, this is very much a feature for nerds. Please stop claiming GNU/Linux is for nerds, that way people will keep believing that bullshit. Pick any modern distribution, use it like normal people do and you'll never even have to know of the existence of a terminal.

If you want this so much, create a fork and add it yourself. THAT is the 'spirit of open source'. Free software, on the other hand...

Either way, why would you want to see the bitrate? If your music files are of bad quality, you'll notice when you're listening to them. If they aren't, you won't notice, and the bitrate doesn't matter because it's impossible to hear any differences between something like q6 ogg and flac anyway. I don't want this feature, because it's pointless, and if @gnumdk added every single kind of request for an 'option', you'd just get yet another Amarok. @bmsimons I also kind of doubt anyone other than the 'nerds' of Lollypop's userbase look at GitHub for feature requests to give thumbs up and down to comments they like or don't like. If it were so popular, I think this would have been suggested two years ago.

**Comment by MichaelTiebesl** [comment]
>  I don't want this feature because it's pointless, and if @gnumdk added every single kind of request for an 'option', you'd just get yet another Amarok. 

I can only agree with this.

**Comment by gnumdk** [comment]
Real nerds do this like this:
`
#!/bin/bash

metadata="$(dbus-send --print-reply --type=method_call  --dest='org.gnome.Lollypop' /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata')"

file="$(echo $metadata|grep 'string "file:///'|grep -v '.cache/lollypop'|cut -d '"' -f2)"

bitrate="$(LANG=C gst-discoverer-1.0 'file:///home/bellegardec/Musique/Collection/Brazil/Bezerra%20da%20Silva/1977%20-%20Partido%20Alto%20Nota%2010%20-%20Bezerra%20e%20Genaro/06%20Chico%20Chora.mp3'|grep '  bitrate:'|cut -d ':' -f2)"

readable=$(awk "BEGIN{print int(($bitrate/1000)+0.5)}")

notify-send "Current bitrate" $readable"kb/s"
`

**Comment by gnumdk** [comment]
Real nerds do this like this:
`#!/bin/bash

metadata="$(dbus-send --print-reply --type=method_call  --dest='org.gnome.Lollypop' /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata')"

file="$(expr "$(echo $metadata)" : '.*"xesam:url" variant string "\([^"]*\)')"


bitrate="$(LANG=C gst-discoverer-1.0 "$file"|grep '  bitrate:'|cut -d ':' -f2)"

readable=$(awk "BEGIN{print int(($bitrate/1000)+0.5)}")

notify-send "Current bitrate" $readable"kb/s"`
