### ISSUE TITLE
YouTube search cannot be enabled

### ISSUE THREAD

**Issue by michael-rapp** [gnumdk/lollypop#737]
-Lollypop version: 0.9.203
-Gtk Version: 3.20.9
-Linux distribution: Arch Linux

The new Lollypop release just landed on my Arch system and I wanted to try out the new YouTube search feature. Unfortunately, the toggle for enabling the YouTube search in the search menu is grayed-out. I did create a Google API project, enabled the Custom Search API as well as the YouTube Data API and entered the API keys in Lollypop's preferences. The API key seems to work as the cover search works fine and the traffic is shown in the Google dashboard. Am I missing something? Maybe an additional package is required for the search to work?
![screenshot from 2016-09-19 15-27-34](https://cloud.githubusercontent.com/assets/6638695/18633858/a3088648-7e7e-11e6-9f05-0ca392a32683.png)

**Comment by gnumdk** [comment]
Let the mouse cursor on the switch :p

**Comment by michael-rapp** [comment]
I am not stupid ;-) The button is actually inactive. I realized that there appears a popover, which says "you need to install youtube-dl" when hovering the checkbox for some time. I installed said package and it works now. It would be a good idea to mark this as an optional dependency in the Arch package.

**Comment by gnumdk** [comment]
I tell it to archlinux packager.

**Comment by michael-rapp** [comment]
Btw, this is a very cool feature!

**Comment by luizzcosta** [comment]
Hi Michael, could you help me?
I've installed Lollypop and I'm loving it so far. However, one thing is bugging me: this API key to I can get to download cover arts directly from Lollypop.
I've looked all over the internet and did not find one single statement about it other than yours.

Could you please teach me how you managed to get it all working for you??

I'd appreciate a lot your help here since I'm new to Linux.

Thanks in advance.

Luiz

**Comment by michael-rapp** [comment]
@luizzcosta I've sent you an e-mail...
