### ISSUE TITLE
Can't save artwork in files

### ISSUE THREAD

**Issue by gnacho** [gnumdk/lollypop#750]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version: 0.9.204
-Gtk Version: 3.20
-Linux distribution: ApricityOS (ArchLinux)

-Describe your bug here:

Can't save artwork in files, the option looks like disabled:
![seleccion_001](https://cloud.githubusercontent.com/assets/10582292/18783290/4bd772d4-818b-11e6-914b-c93350417239.png)

Any ideas?

**Comment by gnumdk** [comment]
Move the cursor on switch...

**Comment by gnacho** [comment]
It's disabled, that's why the grey color is lighter than the other options. Doesn't let me switch right.

**Comment by blackjackshellac** [comment]
FTR, mine too is disabled.

**Comment by gnumdk** [comment]
Move the cursor on the switch and WAIT...

**Comment by julianrichen** [comment]
@gnumdk I have seen a few other issues with people missing this feature, it's not immediately obvious. Maybe instead of putting the pop-over on the switch with an explanation as to why the switch is disabled you but a question mark at the end of the label with an underline? Like so:

```
Save artwork in files (?)
                  .----^----.
                  |   Msg   |
                  ._________.
```

I believe this is more common behaviour for other applications, or at least I have seen other applications do so.

**Comment by gnacho** [comment]
Fixed installing kid3 package. Now works fine :)
